name: HomeReplication Main Build

on:
  push:
    branches:
      - main

jobs:
  BuildCommit:
    strategy:
      fail-fast: true
      matrix:
        build-type: ["Release"]
        malloc-impl: ["libc", "tcmalloc", "jemalloc"]
        prerelease: ["True", "False"]
        exclude:
          - build-type: Debug
            prerelease: "True"
          - build-type: Debug
            malloc-impl: tcmalloc
          - build-type: Debug
            malloc-impl: jemalloc
          - build-type: Release
            malloc-impl: libc
          - prerelease: "True"
            malloc-impl: jemalloc
    uses: ./.github/workflows/build_commit.yml
    with:
      build-type: ${{ matrix.build-type }}
      malloc-impl: ${{ matrix.malloc-impl }}
      prerelease: ${{ matrix.prerelease }}
